### ISSUE TITLE
Define socket messages for basic functionality

### ISSUE THREAD

**Issue by aolivier** [sosolimited/soso-lighting-cms#1]
- [x] Turn on message
- [x] Turn on message
- [x] "Chime" message (may have number associated with it, e.g. chime 1, chime 2, etc.)
- [x]  Send index value with RGB value*

*Just a placeholder for now

**Comment by westhom** [comment]
Additional functionality that would be really useful: knowing whether the Cinder lighting app is connected to the node server. Often on-site internet goes down so it would be useful to communicate to the CMS user that their actions won't change anything, even though a socketio connection to the server is active.

Possible protocol for this:
1. After connecting to socketio server, Cinder socketio client immediately joins the "lighting app" channel.
2. Any new socketio connections receive notice whether or not that channel is populated.
3. If CMS client learns that the channel is empty, show appropriate message, and maybe even disable the web UI until lighting app reconnects.
